# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddfa8ec0b8b1cc020ab11147f9c6a2fd8a7e5268a37d02166b909c3d36f8edc9c5bc28d38d34bc2472373a6c215e67c63dfa65a80ec1cae6a3ed1af69414e5a8

test:
  secret_key_base: 372c816eae75163c2c1d21702629d594571a5130942bac765218bad8194122e8ef19480952e77aba9f53351347fbfaecedf48f2f5fe1fc3286ec1e9de78ba69f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
